### ISSUE TITLE
documentation is not build when using -DBUILD_WITH_DOCUMENTATION=yes

### ISSUE THREAD

**Issue by zkraus** [orpiske/gru#1]
custom target is not executed, and cmake fails when trying to install documentation

Install the project...
-- Install configuration: ""
CMake Error at cmake_install.cmake:36 (file):
  file INSTALL cannot find "/<path>/target/share/doc".

make: *** [Makefile:62: install] Error 1

**Comment by orpiske** [comment]
I'll have to check this one with you today, because I couldn't reproduce it.

**Comment by zkraus** [comment]
fixed with https://github.com/orpiske/gru/commit/b4e8f2cef387801bcbe635f6d9d32348d57d0c21
make documentation is no longer required as the step is now a part of target all.

Fixed by 0.1.0-3
